version: '3.7'
services:
  bot:
    container_name: 'topliga_parser'
    image: topliga_parser
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  custom:
    driver: bridge